# Generated by Django 6.0.3 on 2026-03-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitModel',
            fields=[
                ('exhibit_copy', models.ImageField(blank=True, null=True, upload_to='exhibits')),
                ('serial_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date_received', models.DateField()),
                ('investigator', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('station', models.CharField(max_length=20)),
                ('suspect', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Extracted', 'Extracted'), ('Analyzed', 'Analyzed'), ('Collected', 'Collected'), ('Reported', 'Reported')], default='Pending', max_length=20)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
