# Generated by Django 6.0.3 on 2026-03-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibit_Memo_Form', '0002_exhibitremarksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitmodel',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
