# Generated by Django 6.0.3 on 2026-03-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibit_Memo_Form', '0003_exhibitmodel_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitmodel',
            name='signature',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exhibitmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Extracted', 'Extracted'), ('Analyzed', 'Analyzed'), ('Reported', 'Reported'), ('Collected', 'Collected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ExhibitCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateField()),
                ('collected_by', models.CharField(max_length=20)),
                ('signature', models.CharField(max_length=20)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='Exhibit_Memo_Form.exhibitmodel')),
            ],
        ),
    ]
