# Generated by Django 6.0.3 on 2026-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibit_Memo_Form', '0004_alter_exhibitmodel_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Extracted', 'Extracted'), ('Analyzed', 'Analyzed'), ('Reported', 'Reported'), ('Failed', 'Failed'), ('Collected', 'Collected')], default='Pending', max_length=20),
        ),
    ]
