# Generated by Django 6.0.3 on 2026-03-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibit_Memo_Form', '0005_alter_exhibitmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitmodel',
            options={'ordering': ['-date_received']},
        ),
    ]
