# Generated by Django 6.0.3 on 2026-03-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibit_Memo_Form', '0006_alter_exhibitmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitcollectionmodel',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='exhibitmodel',
            name='signature',
        ),
    ]
